<a href="https://colab.research.google.com/github/greensky0107/self_study/blob/main/Day49_DeepLearningModel_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 4-2. Tensor (Tensor 표현과 연산)

In [1]:
import tensorflow as tf

In [7]:
# 0D Tensor (Scalar) rank 0, shape ()
t0 = tf.constant(1) # tf.constant() 는 상수(constant) tensor를 만듦.
print(t0)
print(tf.rank(t0)) # 축의 개수를 반환.

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)


In [3]:
# 1D Tensor 1차원 tensor (Vector) rank 1, shape(3, )
t1 = tf.constant([1, 2, 3])
print(t1)
print(tf.rank(t1))

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [4]:
# 2D Tensor 2차원 tensor (Matrix) rank 2, shape 3x3(총 9개 data)
# (3, 3)의 2차원 텐서의 차원을 반환하는 함수
t2 = tf.constant([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print(t2)
print(tf.rank(t2))

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [5]:
# 3D Tensor 3차원 tensor rank 3, shape 3x3x3 (총 27개 data)
# (3, 3, 3)의 3차원 텐서를 만들고, 차원을 반환.
t3 = tf.constant([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],

    [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]],

    [[19, 20, 21],
     [22, 23, 24],
     [25, 26, 27]]
])

print(t3)
print(tf.rank(t3))

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]], shape=(3, 3, 3), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


In [8]:
# (3, 3, 3) 크기의 3차원 텐서 생성 (모든 값을 0으로 초기화) - Gemini Code
def get_tensor_dimensions(tensor):
  """TensorFlow 텐서의 차원을 반환."""
  return tensor.shape

# (3, 3, 3) 크기의 3차원 텐서 생성 (모든 값을 0으로 초기화)
my_tf_tensor = tf.zeros((3, 3, 3))

# 함수를 호출하여 차원 확인
dimensions = get_tensor_dimensions(my_tf_tensor)

# 결과 출력
print("### TensorFlow 텐서 ###")
print("생성된 텐서:")
tf.print(my_tf_tensor)
print(f"\n텐서의 차원: {dimensions}")

### TensorFlow 텐서 ###
생성된 텐서:
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]

텐서의 차원: (3, 3, 3)


# 4-3. Tensor Type 및 변환 (Tensor 표현과 연산)

In [9]:
# tensor 생성
i = tf.constant(2)
print(i)

tf.Tensor(2, shape=(), dtype=int32)


In [10]:
# 상수 값 2.0으로 지정하면, 실수형 float32인 텐서를 생성
f = tf.constant(2.)
print(f)

tf.Tensor(2.0, shape=(), dtype=float32)


In [11]:
# 문자열을 값으로 가지는 텐서를 생성할 수도 있으며, 타입은 string이 됨.
s = tf.constant('Susan')
print(s)

tf.Tensor(b'Susan', shape=(), dtype=string)


In [12]:
# 지정한 상수 값의 타입을 보고 자동으로 텐서 타입이 정해지는 것 외에도 필요한 텐서의 타입을 지정하여 생성할 수 있음
# 여기서는 tf.float16으로 16비트 실수형으로 타입을 지정.
f16 = tf.constant(2., dtype=tf.float16)
print(f16)

tf.Tensor(2.0, shape=(), dtype=float16)


In [13]:
# 8비트의 정수형을 지정하여 텐서를 생성
f8 = tf.constant(2, dtype=tf.int8)
print(f8)

tf.Tensor(2, shape=(), dtype=int8)


In [14]:
# 16비트 실수형 tf.float16을 32비트 실수형 tf.float32로 변환.
f32 = tf.cast(f16, tf.float32)
print(f32)

tf.Tensor(2.0, shape=(), dtype=float32)


In [15]:
# 8비트 정수형을 32비트 정수형으로 변환
i32 = tf.cast(f8, tf.int32)
print(i32)

tf.Tensor(2, shape=(), dtype=int32)


In [16]:
# tensor의 shape을 바꾸는 함수.  reshape
x = tf.constant([[1], [2], [3]])
print(x)
print(x.shape)

y = tf.reshape(x, [1, 3])
print(y)
print(y.shape)

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
(3, 1)
tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
(1, 3)


In [17]:
# tensor 전치하여 바꿔서 형상을 바꾸는 역할로 tf.transpose 함수

print(y)
print(tf.transpose(y))
print(y.shape)

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
(1, 3)


In [18]:
print(x)
print(tf.squeeze(x))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [19]:
print(y)
print(tf.expand_dims(y, axis=0))
print(tf.expand_dims(y, axis=1))
print(tf.expand_dims(y, axis=2))

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
tf.Tensor([[[1 2 3]]], shape=(1, 1, 3), dtype=int32)
tf.Tensor([[[1 2 3]]], shape=(1, 1, 3), dtype=int32)
tf.Tensor(
[[[1]
  [2]
  [3]]], shape=(1, 3, 1), dtype=int32)


In [20]:
print(x)
print(tf.split(x, 3))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
[<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[1]], dtype=int32)>, <tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[2]], dtype=int32)>, <tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[3]], dtype=int32)>]


In [21]:
print(x)
print(tf.concat([x, x], axis=0))
print(tf.concat([x, x], axis=1))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
tf.Tensor(
[[1]
 [2]
 [3]
 [1]
 [2]
 [3]], shape=(6, 1), dtype=int32)
tf.Tensor(
[[1 1]
 [2 2]
 [3 3]], shape=(3, 2), dtype=int32)


# 4-4. Tensor Manipulation (Tensor 표현과 연산)

In [22]:
print(tf.constant(2) + tf.constant(2))
print(tf.constant(2) - tf.constant(2))
print(tf.add(tf.constant(2), tf.constant(2)))
print(tf.subtract(tf.constant(2), tf.constant(2)))

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)


In [23]:
print(tf.constant(2) * tf.constant(2))
print(tf.constant(2) / tf.constant(2))
print(tf.multiply(tf.constant(2), tf.constant(2)))
print(tf.divide(tf.constant(2), tf.constant(2)))

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(1.0, shape=(), dtype=float64)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(1.0, shape=(), dtype=float64)


In [24]:
# data type이 다르면 연산 안됨
# print(tf.constant(2) + tf.constant(2.2))
# data type을 맞춰준후 연산해야함
print(tf.cast(tf.constant(2), tf.float32) + tf.constant(2.2))

tf.Tensor(4.2, shape=(), dtype=float32)


In [25]:
# 1차원 텐서 2개를 생성
a=tf.constant([1,2,3])
b=tf.constant([3,4,3])

print(a)
print(b)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([3 4 3], shape=(3,), dtype=int32)


In [26]:
# 1차원 tensor 사칙연산(더하기, 빼기, 곱하기, 나누기).
print(tf.add(a, b))
print(tf.subtract(a, b))

tf.Tensor([4 6 6], shape=(3,), dtype=int32)
tf.Tensor([-2 -2  0], shape=(3,), dtype=int32)


In [27]:
# 크기 (2,2)인 2차원 텐서 2개를 생성
a=tf.constant([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
b=tf.constant([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print(a)
print(b)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [28]:
print(a + b) # element-wise addition
print(a - b) # element-wise subtraction
print(a * b) # element-wise multiplication
print(a @ b) # matrix multiplication
print(a / b) # element-wise division

tf.Tensor(
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 0 0]
 [0 0 0]
 [0 0 0]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 1  4  9]
 [16 25 36]
 [49 64 81]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float64)


In [29]:
print(tf.add(a, b))
print(tf.subtract(a, b))
print(tf.multiply(a, b))
print(tf.matmul(a, b))
print(tf.divide(a, b))

tf.Tensor(
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 0 0]
 [0 0 0]
 [0 0 0]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 1  4  9]
 [16 25 36]
 [49 64 81]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float64)


In [30]:
# reduce_max(): 텐서 값 중에서 최대값을 계산
# argmax(): 최대값의 위치를 반환.
# 예제에서는 [4.0, 5.0, 6.0] 보다 [10.0, 9.0, 8.0]이 다 크기 때문에 [0 0 0]이 아니라 [1 1 1]의 결과를 보여주고 있슴.
# nn.softmax(): 텐서의 값을 0과 1 사이의 값으로 보여줌.
# 예제에서는 [4.0, 5.0, 6.0] 값이 [0.09003057 0.24472848 0.66524094]으로 변환되었고, [10.0, 9.0, 8.0]이 [0.66524094 0.24472848 0.09003057]로 변환됨.

c = tf.constant([[4.0, 5.0, 6.0],
                 [10.0, 9.0, 8.0]])

print(tf.reduce_max(c))
print(tf.argmax(c))
print(tf.nn.softmax(c))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 1 1], shape=(3,), dtype=int64)
tf.Tensor(
[[0.09003057 0.24472848 0.66524094]
 [0.66524094 0.24472848 0.09003057]], shape=(2, 3), dtype=float32)


In [32]:
a = tf.constant([1, 2, 3, 4, 5, 6, 7, 8])
b = tf.constant([[1., 2., 3., 4., 5., 6., 7., 8.]])

# 위에 있는 2개의 텐서를 행렬곱연산이 가능하도록 3차원 텐서로 변환.
a = tf.cast(a, tf.float32) # 행렬곱을 위해 데이터 타입을 float32로 통일

a = tf.reshape(a, (2, 2, 2)) # tensor의 형태를 변환
b = tf.reshape(b, (2, 2, 2)) # tensor의 형태를 변환

print(a@b)

tf.Tensor(
[[[  7.  10.]
  [ 15.  22.]]

 [[ 67.  78.]
  [ 91. 106.]]], shape=(2, 2, 2), dtype=float32)
